// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backEnd.Models;

#nullable disable

namespace backEnd.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20240511095749_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("AgentRequest", b =>
                {
                    b.Property<int>("AgentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AgentsId", "RequestsId");

                    b.HasIndex("RequestsId");

                    b.ToTable("RequestAgents", (string)null);
                });

            modelBuilder.Entity("BudgetUser", b =>
                {
                    b.Property<int>("BudgetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TravelersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BudgetsId", "TravelersId");

                    b.HasIndex("TravelersId");

                    b.ToTable("BudgetTravelers", (string)null);
                });

            modelBuilder.Entity("backEnd.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "phone");

                    b.Property<bool?>("Professional")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "Professional");

                    b.HasKey("Id");

                    b.ToTable("Agents");

                    b.HasAnnotation("Relational:JsonPropertyName", "agents");
                });

            modelBuilder.Entity("backEnd.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("AccountsPrevHandlerIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "accountsPrevHandlerIds");

                    b.Property<bool?>("AccountsProcessed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "AccountsProcessed");

                    b.Property<string>("AirTicketBudget")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "airTicketBudget");

                    b.Property<string>("AmountDisbursedTickets")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "amountDisbursedTickets");

                    b.Property<string>("ArrivalDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "arrival_date");

                    b.Property<string>("AuditPrevHandlerIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "auditPrevHandlerIds");

                    b.Property<bool?>("AuditProcessed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "AuditProcessed");

                    b.Property<bool?>("BeingProcessed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "beingProcessed");

                    b.Property<bool?>("BeingProcessedAccounts")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "beingProcessedAccounts");

                    b.Property<bool?>("BeingProcessedAudit")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "beingProcessedAudit");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "brand");

                    b.Property<string>("CreationDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "creationDate");

                    b.Property<int?>("CurrentAccountsHandlerId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "currentAccountsHandlerId");

                    b.Property<int?>("CurrentAuditHandlerId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "currentAuditHandlerId");

                    b.Property<int?>("CurrentHandlerId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "currentHandlerId");

                    b.Property<bool?>("Custom")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "custom");

                    b.Property<string>("DepartureDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "departure_date");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "destination");

                    b.Property<string>("HotelBudget")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "hotelBudget");

                    b.Property<string>("IncidentalExpense")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "incidentalExpense");

                    b.Property<string>("Initiated")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "initiated");

                    b.Property<string>("NumberOfDays")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "numberOfDays");

                    b.Property<string>("NumberOfTravelers")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "numberOfTravelers");

                    b.Property<string>("PrevHandlerIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "prevHandlerIds");

                    b.Property<bool?>("Processed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "processed");

                    b.Property<bool?>("Rejected")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rejected");

                    b.Property<bool?>("SeekingAccountsApprovalForTickets")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "seekingAccountsApprovalForTickets");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "subject");

                    b.Property<string>("TicketsAccountHolderNumber")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ticketsAccountHolderName");

                    b.Property<string>("TicketsAccountNumber")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "ticketsAccountNumber");

                    b.Property<bool?>("TicketsApprovedByAccounts")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "ticketsApprovedByAccounts");

                    b.Property<bool?>("TicketsMoneyDisbursed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "ticketsMoneyDisbursed");

                    b.Property<string>("TotalBookingCost")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "totalBookingCost");

                    b.Property<string>("TotalTripBudget")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "totalTripBudget");

                    b.Property<string>("TransportExpense")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "transportExpense");

                    b.Property<string>("TripId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "tripId");

                    b.HasKey("Id");

                    b.ToTable("Budgets");

                    b.HasAnnotation("Relational:JsonPropertyName", "budget");
                });

            modelBuilder.Entity("backEnd.Models.BudgetTicketApprovals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("BudgetTicketApprovals");
                });

            modelBuilder.Entity("backEnd.Models.Cost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("Item")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "item");

                    b.Property<string>("ItemCost")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "itemCost");

                    b.Property<string>("NumberOfItems")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "numberOfItems");

                    b.Property<int?>("RequestId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "requestId");

                    b.Property<int?>("TotalItemCost")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "totalItemCost");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Costs");

                    b.HasAnnotation("Relational:JsonPropertyName", "costs");
                });

            modelBuilder.Entity("backEnd.Models.ExpenseReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("AmountDisbursed")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "amountDisbursed");

                    b.Property<string>("Approvals")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "approvals");

                    b.Property<string>("BankAccountHolderName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "bankAccountHolderName");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "bankAccountNumber");

                    b.Property<int?>("CurrentHandlerId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "currentHandlerId");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "department");

                    b.Property<bool?>("Disbursed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "disbursed");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "employeeId");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "employeeName");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "endDate");

                    b.Property<string>("PrevHandlerIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "prevHandlerIds");

                    b.Property<bool?>("Processed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "processed");

                    b.Property<bool?>("Rejected")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rejected");

                    b.Property<int?>("RequestId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "requestId");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "startDate");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<bool?>("Submitted")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "submitted");

                    b.Property<bool?>("SupervisorApproved")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "supervisorApproved");

                    b.Property<bool?>("TravelManagerSubmitted")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "travelManagerSubmitted");

                    b.HasKey("Id");

                    b.HasIndex("CurrentHandlerId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("ExpenseReports");

                    b.HasAnnotation("Relational:JsonPropertyName", "currentExpenseReportsHandled");
                });

            modelBuilder.Entity("backEnd.Models.Expenses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("Amount")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "amount");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<int?>("ExpenseReportId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "expenseReportId");

                    b.Property<string>("ExpenseType")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "expenseType");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "notes");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "source");

                    b.Property<string>("Voucher")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "invoice");

                    b.Property<bool?>("VoucherGiven")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "voucherGiven");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseReportId");

                    b.ToTable("Expenses");

                    b.HasAnnotation("Relational:JsonPropertyName", "expenses");
                });

            modelBuilder.Entity("backEnd.Models.FlyerNos", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("Airline")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "airline");

                    b.Property<string>("Number")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "number");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FlyerNos");

                    b.HasAnnotation("Relational:JsonPropertyName", "flyerNos");
                });

            modelBuilder.Entity("backEnd.Models.HotelApprovals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuotationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.HasIndex("UserId");

                    b.ToTable("HotelApprovals");
                });

            modelBuilder.Entity("backEnd.Models.HotelForBrands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "brand");

                    b.Property<string>("BrandOfficeAddress")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "brandOfficeAddress");

                    b.HasKey("Id");

                    b.ToTable("HotelForBrands");

                    b.HasAnnotation("Relational:JsonPropertyName", "hotelForBrands");
                });

            modelBuilder.Entity("backEnd.Models.HotelInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "filePath");

                    b.Property<string>("Filename")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "filename");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("HotelInvoices");
                });

            modelBuilder.Entity("backEnd.Models.HotelLocations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<int?>("HotelForBrandsId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hotelForBrandsId");

                    b.Property<string>("LocationName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "locationName");

                    b.HasKey("Id");

                    b.HasIndex("HotelForBrandsId");

                    b.ToTable("HotelLocations");

                    b.HasAnnotation("Relational:JsonPropertyName", "hotelLocations");
                });

            modelBuilder.Entity("backEnd.Models.HotelQuotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Approved")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "approved");

                    b.Property<bool?>("Booked")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "booked");

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "confirmed");

                    b.Property<bool?>("Custom")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "custom");

                    b.Property<bool?>("Hovered")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hovered");

                    b.Property<Guid?>("Linker")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "linker");

                    b.Property<string>("QuotationText")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "quotationText");

                    b.Property<string>("QuoteGiver")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "quoteGiver");

                    b.Property<int?>("RequestId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "requestId");

                    b.Property<string>("RequestIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "requestIds");

                    b.Property<bool?>("Selected")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "selected");

                    b.Property<string>("TotalCosts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "totalCosts");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("RequestId");

                    b.ToTable("HotelQuotations");

                    b.HasAnnotation("Relational:JsonPropertyName", "hotelQuotations");
                });

            modelBuilder.Entity("backEnd.Models.HotelQuotationInvoices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuotationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("QuotationId");

                    b.ToTable("HotelQuotationInvoices");
                });

            modelBuilder.Entity("backEnd.Models.Hotels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("HotelAddress")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "hotelAddress");

                    b.Property<int?>("HotelLocationsId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hotelLocationsId");

                    b.Property<string>("HotelName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "hotelName");

                    b.Property<string>("Rooms")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "rooms");

                    b.HasKey("Id");

                    b.HasIndex("HotelLocationsId");

                    b.ToTable("Hotels");

                    b.HasAnnotation("Relational:JsonPropertyName", "hotels");
                });

            modelBuilder.Entity("backEnd.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_Id");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "Date");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "Event");

                    b.Property<int?>("FromId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "FromId");

                    b.Property<int?>("RequestId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "RequestId");

                    b.Property<int?>("ToId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "ToId");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Logs");

                    b.HasAnnotation("Relational:JsonPropertyName", "logs");
                });

            modelBuilder.Entity("backEnd.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "content");

                    b.Property<int?>("RequestId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "requestId");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Messages");

                    b.HasAnnotation("Relational:JsonPropertyName", "messages");
                });

            modelBuilder.Entity("backEnd.Models.MoneyReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("AdvanceMoneyInHand")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "advanceMoneyInHand");

                    b.Property<string>("AmountDisbursed")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "amountDisbursed");

                    b.Property<string>("Approvals")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "approvals");

                    b.Property<string>("AsAdvanceAgainst")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "asAdvanceAgainst");

                    b.Property<string>("BankAccountHolderName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "bankAccountHolderName");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "bankAccountNumber");

                    b.Property<int?>("CurrentHandlerId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "currentHandlerId");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<string>("Designation")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "designation");

                    b.Property<bool?>("Disbursed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "disbursed");

                    b.Property<string>("I")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "i");

                    b.Property<string>("PrevHandlerIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "prevHandlerIds");

                    b.Property<bool?>("Processed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "processed");

                    b.Property<bool?>("Rejected")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rejected");

                    b.Property<int?>("RequestId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "requestId");

                    b.Property<string>("RequiredTK")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "requiredTK");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "section");

                    b.Property<string>("SerialNo")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "serialNo");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<bool?>("Submitted")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "submitted");

                    b.Property<bool?>("SupervisorApproved")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "supervisorApproved");

                    b.Property<string>("Taka")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "taka");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "unit");

                    b.HasKey("Id");

                    b.HasIndex("CurrentHandlerId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("MoneyReceipts");

                    b.HasAnnotation("Relational:JsonPropertyName", "currentReceiptsHandled");
                });

            modelBuilder.Entity("backEnd.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("Event")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "event");

                    b.Property<int?>("From")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "from");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "message");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "sourceId");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "time");

                    b.Property<int?>("To")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "to");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("backEnd.Models.Quotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<int?>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Approved")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "approved");

                    b.Property<bool?>("Booked")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "booked");

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "confirmed");

                    b.Property<bool?>("Custom")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "custom");

                    b.Property<bool?>("Hovered")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hovered");

                    b.Property<Guid?>("Linker")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "linker");

                    b.Property<string>("QuotationText")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "quotationText");

                    b.Property<string>("QuoteGiver")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "quoteGiver");

                    b.Property<int?>("RequestId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "requestId");

                    b.Property<string>("RequestIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "requestIds");

                    b.Property<bool?>("Selected")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "selected");

                    b.Property<string>("TotalCosts")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "totalCosts");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("RequestId");

                    b.ToTable("Quotations");

                    b.HasAnnotation("Relational:JsonPropertyName", "quotations");
                });

            modelBuilder.Entity("backEnd.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("AccomodationRequired")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "accomodationRequired");

                    b.Property<string>("Activities")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "activities");

                    b.Property<int?>("AgentNumbers")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "agentNumbers");

                    b.Property<string>("Approvals")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "approvals");

                    b.Property<bool?>("BeingProcessed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "beingProcessed");

                    b.Property<string>("Best")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "best");

                    b.Property<string>("BestHotel")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "bestHotel");

                    b.Property<bool?>("Booked")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "booked");

                    b.Property<int?>("BudgetId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "budgetId");

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "confirmed");

                    b.Property<int?>("CurrentHandlerId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "currentHandlerId");

                    b.Property<bool?>("Custom")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "custom");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "date");

                    b.Property<bool?>("DepartmentHeadApproved")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "departmentHeadApproved");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "destination");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "endDate");

                    b.Property<bool?>("ExpenseReportGiven")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "expenseReportGiven");

                    b.Property<bool?>("HotelBooked")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hotelBooked");

                    b.Property<bool?>("HotelConfirmed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hotelConfirmed");

                    b.Property<bool?>("HotelInvoiceUploaded")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "hotelInvoiceUploaded");

                    b.Property<bool?>("InTrip")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "inTrip");

                    b.Property<string>("Items")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "items");

                    b.Property<string>("Meetings")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "meetings");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "mode");

                    b.Property<int>("MoneyReceiptId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "moneyReceiptId");

                    b.Property<bool>("MoneyReceiptSubmitted")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "moneyReceiptSubmitted");

                    b.Property<string>("Number")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "number");

                    b.Property<string>("NumberOfNights")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "numberOfNights");

                    b.Property<string>("Objectives")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "objectives");

                    b.Property<bool?>("PermanentlyRejected")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "permanentlyRejected");

                    b.Property<string>("Personnel")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "personnel");

                    b.Property<string>("PrevHandlerIds")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "prevHandlerIds");

                    b.Property<bool?>("Processed")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "processed");

                    b.Property<string>("Purpose")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "purpose");

                    b.Property<string>("RequestBudget")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "requestBudget");

                    b.Property<int?>("RequesterId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "requesterId");

                    b.Property<bool?>("SeekingHotelInvoices")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "seekingHotelInvoices");

                    b.Property<bool?>("SeekingInvoices")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "seekingInvoices");

                    b.Property<bool?>("Selected")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "selected");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "startDate");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<bool?>("SupervisorApproved")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "supervisorApproved");

                    b.Property<bool?>("TicketInvoiceUploaded")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "ticketInvoiceUploaded");

                    b.Property<int?>("TotalCost")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "totalCost");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "tripId");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CurrentHandlerId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Requests");

                    b.HasAnnotation("Relational:JsonPropertyName", "currentHandled");
                });

            modelBuilder.Entity("backEnd.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("backEnd.Models.TicketApprovals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuotationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.HasIndex("UserId");

                    b.ToTable("TicketApprovals");
                });

            modelBuilder.Entity("backEnd.Models.TicketInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "filePath");

                    b.Property<string>("Filename")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "filename");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("TicketInvoices");
                });

            modelBuilder.Entity("backEnd.Models.TicketQuotationInvoices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuotationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("QuotationId");

                    b.ToTable("TicketQuotationInvoices");
                });

            modelBuilder.Entity("backEnd.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "_id");

                    b.Property<bool?>("Available")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "available");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "department");

                    b.Property<string>("Designation")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "designation");

                    b.Property<string>("EmpCode")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "empCode");

                    b.Property<string>("EmpId")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "empId");

                    b.Property<string>("EmpName")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "empName");

                    b.Property<string>("Extension")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "extension");

                    b.Property<string>("HasFrequentFlyerNo")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "hasFrequentFlyerNo");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<string>("MailAddress")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "mailAddress");

                    b.Property<string>("MobileNo")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "mobileNo");

                    b.Property<int?>("Numbers")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "numbers");

                    b.Property<string>("PassportNo")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "passportNo");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "password");

                    b.Property<string>("PreferenceImage")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "preferenceImage");

                    b.Property<string>("Preferences")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "preferences");

                    b.Property<int?>("Raters")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "raters");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "rating");

                    b.Property<string>("Section")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "section");

                    b.Property<int?>("SuperVisorId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "superVisorId");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "team");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "unit");

                    b.Property<string>("UserType")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "userType");

                    b.Property<string>("Wing")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "wing");

                    b.Property<int?>("ZonalHeadId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "zonalHeadId");

                    b.HasKey("Id");

                    b.HasIndex("SuperVisorId");

                    b.HasIndex("ZonalHeadId");

                    b.ToTable("Users");

                    b.HasAnnotation("Relational:JsonPropertyName", "currentHandler");
                });

            modelBuilder.Entity("backEnd.Models.UserRoles", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("AgentRequest", b =>
                {
                    b.HasOne("backEnd.Models.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backEnd.Models.Request", null)
                        .WithMany()
                        .HasForeignKey("RequestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetUser", b =>
                {
                    b.HasOne("backEnd.Models.Budget", null)
                        .WithMany()
                        .HasForeignKey("BudgetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backEnd.Models.User", null)
                        .WithMany()
                        .HasForeignKey("TravelersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backEnd.Models.BudgetTicketApprovals", b =>
                {
                    b.HasOne("backEnd.Models.Budget", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backEnd.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backEnd.Models.Cost", b =>
                {
                    b.HasOne("backEnd.Models.Request", "Request")
                        .WithMany("Costs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("backEnd.Models.ExpenseReport", b =>
                {
                    b.HasOne("backEnd.Models.User", "CurrentHandler")
                        .WithMany("CurrentExpenseReportsHandled")
                        .HasForeignKey("CurrentHandlerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backEnd.Models.Request", "Request")
                        .WithOne("ExpenseReport")
                        .HasForeignKey("backEnd.Models.ExpenseReport", "RequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentHandler");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("backEnd.Models.Expenses", b =>
                {
                    b.HasOne("backEnd.Models.ExpenseReport", "ExpenseReport")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ExpenseReport");
                });

            modelBuilder.Entity("backEnd.Models.FlyerNos", b =>
                {
                    b.HasOne("backEnd.Models.User", "User")
                        .WithMany("FlyerNos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("backEnd.Models.HotelApprovals", b =>
                {
                    b.HasOne("backEnd.Models.HotelQuotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backEnd.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backEnd.Models.HotelLocations", b =>
                {
                    b.HasOne("backEnd.Models.HotelForBrands", "HotelForBrands")
                        .WithMany("Locations")
                        .HasForeignKey("HotelForBrandsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("HotelForBrands");
                });

            modelBuilder.Entity("backEnd.Models.HotelQuotation", b =>
                {
                    b.HasOne("backEnd.Models.Agent", null)
                        .WithMany("HotelQuotations")
                        .HasForeignKey("AgentId");

                    b.HasOne("backEnd.Models.Request", "Request")
                        .WithMany("HotelQuotations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("backEnd.Models.HotelQuotationInvoices", b =>
                {
                    b.HasOne("backEnd.Models.HotelInvoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backEnd.Models.HotelQuotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("backEnd.Models.Hotels", b =>
                {
                    b.HasOne("backEnd.Models.HotelLocations", "HotelLocation")
                        .WithMany("Hotels")
                        .HasForeignKey("HotelLocationsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("HotelLocation");
                });

            modelBuilder.Entity("backEnd.Models.Log", b =>
                {
                    b.HasOne("backEnd.Models.Request", "Request")
                        .WithMany("Logs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("backEnd.Models.Message", b =>
                {
                    b.HasOne("backEnd.Models.Request", "Request")
                        .WithMany("Messages")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("backEnd.Models.MoneyReceipt", b =>
                {
                    b.HasOne("backEnd.Models.User", "CurrentHandler")
                        .WithMany("CurrentReceiptsHandled")
                        .HasForeignKey("CurrentHandlerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backEnd.Models.Request", "Request")
                        .WithOne("MoneyReceipt")
                        .HasForeignKey("backEnd.Models.MoneyReceipt", "RequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentHandler");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("backEnd.Models.Quotation", b =>
                {
                    b.HasOne("backEnd.Models.Agent", null)
                        .WithMany("Quotations")
                        .HasForeignKey("AgentId");

                    b.HasOne("backEnd.Models.Request", "Request")
                        .WithMany("Quotations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("backEnd.Models.Request", b =>
                {
                    b.HasOne("backEnd.Models.Budget", "Budget")
                        .WithMany("Requests")
                        .HasForeignKey("BudgetId");

                    b.HasOne("backEnd.Models.User", "CurrentHandler")
                        .WithMany("CurrentHandled")
                        .HasForeignKey("CurrentHandlerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backEnd.Models.User", "Requester")
                        .WithMany("Requests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Budget");

                    b.Navigation("CurrentHandler");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("backEnd.Models.TicketApprovals", b =>
                {
                    b.HasOne("backEnd.Models.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backEnd.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backEnd.Models.TicketQuotationInvoices", b =>
                {
                    b.HasOne("backEnd.Models.TicketInvoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backEnd.Models.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("backEnd.Models.User", b =>
                {
                    b.HasOne("backEnd.Models.User", "SuperVisor")
                        .WithMany("SuperVised")
                        .HasForeignKey("SuperVisorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("backEnd.Models.User", "ZonalHead")
                        .WithMany("Head")
                        .HasForeignKey("ZonalHeadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SuperVisor");

                    b.Navigation("ZonalHead");
                });

            modelBuilder.Entity("backEnd.Models.UserRoles", b =>
                {
                    b.HasOne("backEnd.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backEnd.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backEnd.Models.Agent", b =>
                {
                    b.Navigation("HotelQuotations");

                    b.Navigation("Quotations");
                });

            modelBuilder.Entity("backEnd.Models.Budget", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("backEnd.Models.ExpenseReport", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("backEnd.Models.HotelForBrands", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("backEnd.Models.HotelLocations", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("backEnd.Models.Request", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("ExpenseReport");

                    b.Navigation("HotelQuotations");

                    b.Navigation("Logs");

                    b.Navigation("Messages");

                    b.Navigation("MoneyReceipt")
                        .IsRequired();

                    b.Navigation("Quotations");
                });

            modelBuilder.Entity("backEnd.Models.User", b =>
                {
                    b.Navigation("CurrentExpenseReportsHandled");

                    b.Navigation("CurrentHandled");

                    b.Navigation("CurrentReceiptsHandled");

                    b.Navigation("FlyerNos");

                    b.Navigation("Head");

                    b.Navigation("Requests");

                    b.Navigation("SuperVised");
                });
#pragma warning restore 612, 618
        }
    }
}
